### ISSUE TITLE
Special characters in password cause authentication to fail

### ISSUE THREAD

**Issue by moeskerv** [antechrestos/python-netatmo-client#1]
Thanks for providing this great python lib. I tried to use it today and got the issue that the token request using client credentials failed with an error "invalid_grant".

It turned out that this was cause by the password I used for my Netatmo account: "5\r{SM0_~gpG". While the passwort was working when trying some API calls using Postman, the request failed using the pyhton client. Changing the passwort to an easier one not using special characters worked.

I guess that the escaping special characters would fix the issue.

BR,
Volker

**Comment by antechrestos** [comment]
@moeskerv ,

thank for your return. 

Did you enter the password as a python string such as  ̀"5\r{SM0_~gpG"` ? Because if you did so, in python, `\r` is not seen as two characters but as a single one: carrriage return.
Did you try with the the chain   ̀"5\\r{SM0_~gpG"`
I added [a test](https://github.com/antechrestos/python-netatmo-client/blob/master/test/test_token.py)  that illustrates this.
As you can see it reads [a raw file](https://github.com/antechrestos/python-netatmo-client/blob/master/test/fixtures/oauth2/token/client_credentials.txt) and compares that data posted is the one we expect.

Please tell me if it worked.

**Comment by moeskerv** [comment]
Hi again,

I can confirm your feedback. Escaping "\r" in String does the trick. Thanks!

BR,
Volker
